---
- hosts: all

  tasks:
    - apt: name={{ item }} state=latest
      become: yes
      with_items:
        - ack-grep
        - exuberant-ctags
        - curl
        - python-apt
        - python-pycurl
        - python-dev
        - python-setuptools
        - flex
      when: ansible_distribution == 'Ubuntu'
      tags: always

    - command: mkdir -p $HOME/.go
      tags:
        - all
        - go

    - git: repo="{{ item.repo }}"
        dest="/var/tmp/{{ item.name }}"
        version="{{ item.version }}"
        accept_hostkey=yes
      with_items:
        - { repo: 'git://github.com/pote/gpm.git', version: 'v1.3.2', name: 'gpm' }
        - { repo: 'git://github.com/pote/gvp.git', version: 'v0.3.0', name: 'gvp' }
      tags:
        - all
        - go

    - shell: 'cd /var/tmp/{{ item }}; ./configure; sudo make install'
      with_items:
        - gpm
        - gvp
      tags:
        - all
        - go

    - lineinfile: dest="~/.bash_profile" state=present create=yes line='{{ item }}'
      with_items:
       - 'export GOPATH=$HOME/.go'
       - 'export GOROOT=/usr/lib/go'
       - 'export PATH=$PATH:$GOPATH/bin'
       - 'export PATH=$PATH:$GOROOT/bin'
      tags:
        - all
        - go

    - name: Install Go deps
      shell: 'GOPATH=$HOME/.go /usr/bin/go get {{item}}'
      with_items:
        - github.com/nsf/gocode
        - github.com/k0kubun/pp
        - golang.org/x/tools/cmd/godoc
      tags:
        - all
        - go

    - git: repo=git://github.com/direnv/direnv.git
        dest=/var/tmp/direnv
        accept_hostkey=yes
      tags:
        - all
        - direnv
    - command: sudo make install
        chdir=/var/tmp/direnv
      tags:
        - all
        - direnv

    - easy_install: name=pip
      become: yes
      tags: always

    - shell: curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
      become: yes
      tags:
        - all
        - php

    - shell: composer global require "squizlabs/php_codesniffer=*"
      # become: yes
      tags:
        - all
        - php

    - pip: name={{ item }} state=latest
      become: yes
      with_items:
        - pylint
        - ansible-lint
        - bashate
      tags: always

    - shell: cabal update && cabal install ghc-mod
      tags:
        - all
        - haskell

    - gem: name={{ item }} state=latest user_install=no
      with_items:
        - haml-lint
        - ruby-lint
        - sqlint
        - rubocop
        - brakeman
      tags:
        - all
        - ruby

    - npm: name={{ item }} global=yes state=latest
      become: yes
      with_items:
        - bower
        - js-yaml
        - eslint # NOTE: http://eslint.org/docs/configuring/ for enabling jsx
        - babel-eslint
        - eslint-plugin-react
        - jsonlint
      tags:
        - all
        - node
