---
- hosts: all

  tasks:
    - apt: name={{ item }} state=latest
      become: yes
      with_items:
        - ack-grep
        - clang-format-3.6
        - clang-3.6
        - llvm
        - exuberant-ctags
        - curl
        - python-apt
        - python-pycurl
        - python-dev
        - python-setuptools
        - flex
      when: ansible_distribution == 'Ubuntu'
      tags: always

    - easy_install: name=pip
      become: yes
      tags: always

    - git: repo=git://github.com/ten0s/syntaxerl.git dest=/var/tmp/syntaxerl
      tags:
        - all
        - erlang

    - shell: cd /var/tmp/syntaxerl && make
      tags:
        - all
        - erlang

    - copy: src=/var/tmp/syntaxerl/syntaxerl dest=/usr/local/bin/syntaxerl
      become: yes
      tags:
        - all
        - erlang

    - shell: curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
      become: yes
      ignore_errors: yes
      tags:
        - all
        - php

    - shell: composer global require "squizlabs/php_codesniffer=*"
      # become: yes
      ignore_errors: yes
      tags:
        - all
        - php

    - pip: name={{ item }} state=latest
      become: yes
      with_items:
        - pylint
        - ansible-lint
        - grip
        - bashate
      tags: always

    - shell: cabal update
      ignore_errors: yes
      tags:
        - all
        - haskell

    - shell: stack install {{ item }}
      ignore_errors: yes
      with_items:
        - ghc-mod
      tags:
        - all
        - haskell

    - lineinfile:
        state: present
        dest: ~/.bashrc
        regexp: '.cabal/bin'
        line: 'export PATH="$PATH:$HOME/.cabal/bin"'
      tags:
        - all
        - haskell

    - gem: name={{ item }} state=latest user_install=no
      become: yes
      ignore_errors: yes
      with_items:
        - haml-lint
        - ruby-lint
        - sqlint
        - rubocop
      tags:
        - all
        - ruby

    - npm: name={{ item }} global=yes state=latest
      become: yes
      ignore_errors: yes
      with_items:
        - bower
        - js-yaml
        - eslint # NOTE: http://eslint.org/docs/configuring/ for enabling jsx
        - eslint-config-airbnb
        - eslint-plugin-react
        - jsonlint
      tags:
        - all
        - node
