---
- hosts: localhost
  vars:
    dotfiles: ~/dotfiles
  tasks:
    - file: src={{ dotfiles }}/{{ item }} dest=~/.{{ item }} state=link
      with_items:
        - vimrc
        - gitconfig
    - git: repo=https://github.com/gmarik/Vundle.vim.git dest=~/.vim/bundle/Vundle.vim

    - homebrew: state=present name=ctags install_options="--with-exuberant-ctags"
    - homebrew: name={{ item }}
      with_items:
        - vim
        - imagemagick
        - ack
        - npm
        - postgresql
        - redis
        - erlang
        - leiningen
        - bash-completion
        - rbenv
        - ruby-build
        - phantomjs
        - elasticsearch
        - brew install python
        - brew install python3
        # - https://raw.github.com/eugeneoden/homebrew/eca9de1/Library/Formula/sshpass.rb

    # - lineinfile: dest=~/.bash_profile state=present
    #     line="eval \"$(rbenv init -)\""

    - shell: rbenv install 2.1.2
    - shell: rbenv global 2.1.2
      tags: [ruby]

    - shell: ln -sfv /usr/local/opt/postgresql/*.plist ~/Library/LaunchAgents
    - shell: ln -sfv /usr/local/opt/redis/*.plist ~/Library/LaunchAgents
    - shell: ln -sfv /usr/local/opt/elasticsearch/*.plist ~/Library/LaunchAgents

    - gem: name={{ item }} state=present
      with_items:
        - bundler
        - haml-lint
        - ruby-lint
        - rubocop
        - sass
      tags: [ruby]

    - shell: rbenv rehash

    - npm: name={{ item }} global=yes
      with_items:
        - bower
        - js-yaml
        - jsxhint
        - eslint
        - jsonlint
        - grunt-cli

    - easy_install: name=pip
      sudo: yes
    - pip: name={{ item }}
      sudo: yes
      with_items:
        - pylint

    # - lineinfile: dest="~/.bash_profile" state=present
    #               line="set -o vi"
    #                 source /Library/Developer/CommandLineTools/usr/share/git-core/git-prompt.sh
    #                  export PS1='$(__git_ps1) \w\$ '
