# The real shell config. ~/.zshrc is generated by mise and contains nothing but
# the line that sources this file, so anything that has to survive a fresh
# machine lives here.

# ~/.local/bin is where `uv tool install` puts its binaries (mypy, ty, prek and
# the rest), and nothing adds it to PATH on its own. The shims at the tail are a
# fallback for processes that never run `mise activate` — GUI apps, launchd —
# because inside this shell activate resolves the tools to their real paths and
# the shims are never reached.
export PATH="$HOME/.local/bin:$PATH:$HOME/.local/share/mise/shims"

# Homebrew's prefix, where the brew formulae live. Deliberately before
# `mise activate`: brew shellenv prepends its own bin, and the mise paths have
# to end up in front of it, or a brew-installed node would shadow the version
# pinned in [tools].
[ -x /opt/homebrew/bin/brew ] && eval "$(/opt/homebrew/bin/brew shellenv)"

eval "$(mise activate zsh)"

# Completions. Almost nothing here ships a completion file — each tool prints
# one from a subcommand instead, and the flag differs per tool. misecompsync
# knows those flags for 130-odd tools and writes the files; the mise hooks that
# call it are in mise.toml, and the four tools it does not know about are in
# zsh/completions-registry.toml. Nothing is generated at startup — these are two
# directories of finished files, and they only have to be on fpath before
# compinit reads it. The second one is where `mise completion zsh --install`
# puts mise's own, kept apart so that `misecompsync clean` cannot reach it.
fpath=(
  "$HOME/.local/share/mise-completions/zsh"
  "$HOME/.local/share/zsh/site-functions"
  $fpath
)

# oh-my-zsh used to be the only thing calling compinit. Without this line a
# fresh machine has no completion at all.
autoload -Uz compinit && compinit

# oh-my-zsh plugins, sourced as plain files. They are ordinary zsh scripts and
# need nothing from the framework — no $ZSH, no plugins=(), no oh-my-zsh.sh.
# The clone they come from is declared in [bootstrap.repos]. Sourced before
# atuin so that atuin's ctrl-r wins over the vi-mode binding.
for _plugin in git vi-mode eza; do
  _file="$HOME/.oh-my-zsh/plugins/$_plugin/$_plugin.plugin.zsh"
  [ -r "$_file" ] && source "$_file"
done
unset _plugin _file

eval "$(atuin init zsh)"
# zoxide binds `cd` itself rather than the default `z`: cd is what actually gets
# typed here, so it is the one worth making frecency-aware.
eval "$(zoxide init zsh --cmd cd)"
eval "$(starship init zsh)"

# Machine-local and untracked — tokens and anything else that must not reach a
# public repo. See "What is still manual" in the README.
[ -f "$HOME/.config/zsh/local.zsh" ] && source "$HOME/.config/zsh/local.zsh"
